(component
  (component $another:thing (;0;)
    (type (;0;)
      (component
        (type (;0;)
          (instance
            (type (;0;) (record (field "foo" string)))
            (export (;1;) "my-record" (type (eq 0)))
          )
        )
        (export (;0;) "another:thing/something" (instance (type 0)))
      )
    )
    (export (;1;) "something" (type 0))
  )
  (component $third:pkg (;1;)
    (type (;0;)
      (component
        (type (;0;)
          (instance
            (type (;0;) (record (field "foo" string)))
            (export (;1;) "other-record" (type (eq 0)))
          )
        )
        (export (;0;) "third:pkg/things" (instance (type 0)))
      )
    )
    (export (;1;) "things" (type 0))
  )
  (component $foo:bar (;2;)
    (type (;0;)
      (component
        (type (;0;)
          (component
            (type (;0;)
              (instance
                (type (;0;) (record (field "foo" string)))
                (export (;1;) "my-record" (type (eq 0)))
              )
            )
            (import "another:thing/something" (instance (;0;) (type 0)))
            (type (;1;)
              (instance
                (type (;0;) (record (field "foo" string)))
                (export (;1;) "other-record" (type (eq 0)))
              )
            )
            (import "third:pkg/things" (instance (;1;) (type 1)))
          )
        )
        (export (;0;) "foo:bar/this-world" (component (type 0)))
      )
    )
    (export (;1;) "this-world" (type 0))
  )
  (@custom "package-docs" "\00{}")
  (@custom "package-docs" "\00{}")
  (@custom "package-docs" "\00{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
